# Generated by Django 5.2.4 on 2026-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clientid', models.AutoField(db_column='ClientID', primary_key=True, serialize=False)),
                ('tipodocumento', models.CharField(blank=True, db_column='TipoDocumento', max_length=10, null=True)),
                ('numerodocumento', models.CharField(db_column='NumeroDocumento', max_length=20)),
                ('razonsocial', models.CharField(db_column='RazonSocial', max_length=200)),
                ('nombrecomercial', models.CharField(blank=True, db_column='NombreComercial', max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=500, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True)),
                ('pais', models.CharField(blank=True, db_column='Pais', max_length=100, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('creadopor', models.IntegerField(blank=True, db_column='CreadoPor', null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='FechaCreacion', null=True)),
                ('modificadopor', models.IntegerField(blank=True, db_column='ModificadoPor', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='FechaModificacion', null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'dbo.Clientes',
                'managed': False,
            },
        ),
    ]
