# Generated by Django 5.1 on 2026-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentoid', models.AutoField(db_column='DepartamentoID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='FechaCreacion', null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'dbo.Departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('permisoid', models.AutoField(db_column='PermisoID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('codigo', models.CharField(db_column='Codigo', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
                ('modulo', models.CharField(blank=True, db_column='Modulo', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'dbo.Permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rolid', models.AutoField(db_column='RolID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
                ('nivelacceso', models.IntegerField(blank=True, db_column='NivelAcceso', null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'dbo.Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermisos',
            fields=[
                ('rolpermisoid', models.AutoField(db_column='RolPermisoID', primary_key=True, serialize=False)),
                ('otorgado', models.BooleanField(blank=True, db_column='Otorgado', null=True)),
                ('fechaasignacion', models.DateTimeField(blank=True, db_column='FechaAsignacion', null=True)),
            ],
            options={
                'verbose_name': 'Rol Permiso',
                'verbose_name_plural': 'Rol Permisos',
                'db_table': 'dbo.RolPermisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioid', models.AutoField(db_column='UsuarioID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('nombreusuario', models.CharField(db_column='NombreUsuario', max_length=50)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='FechaCreacion', null=True)),
                ('ultimoacceso', models.DateTimeField(blank=True, db_column='UltimoAcceso', null=True)),
                ('intentosfallidos', models.IntegerField(blank=True, db_column='IntentosFallidos', null=True)),
                ('bloqueado', models.BooleanField(blank=True, db_column='Bloqueado', null=True)),
                ('fechabloqueo', models.DateTimeField(blank=True, db_column='FechaBloqueo', null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'dbo.Usuarios',
                'managed': False,
            },
        ),
    ]
